name = "avrada_mcu"
description = "Device (MCU) specific definitions for AVR microcontrollers"
version = "2.2.1"

authors = ["Rolf Ebert"]
maintainers = ["Rolf Ebert <rolf.ebert.gcc@gmx.de>"]
maintainers-logins = ["RREE"]
licenses = "GPL-2.0-or-later WITH GCC-exception-3.1"
website = "https://github.com/RREE/AVRAda_Doc/"
tags = ["avr", "embedded", "rts"]

[[depends-on]]
gnat_avr_elf = "^11 | ^12.2 | ^13.2"
avrada_rts = "^2.0.2"

